In [10]:
import ast
import pandas as pd

In [65]:
df = pd.read_csv('rnn_task_environments_2021-03-17.csv', header=0)

In [66]:
df

,ID,sequence,coordinates,start_coordinates,strong_k,mid_k,food_k,containment
0,a1,pocgkr,"p: (0.008034,0.957082,0.6890539999999999);o: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
1,a3,cgwpcfks,"c: (-0.525007,0.923283,0.438);g: (-0.595001,1....","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
2,a5,kfsfkspwg,"k: (-0.07699199999999999,0.733425,0.531662);f:...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
3,a11,pfkswkfsococg,"p: (0.008034,0.957082,0.6890539999999999);p: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
4,a13,wptgkfsoc,"w: (-0.196022,1.35572,0.466005);p: (0.008034,0...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
...,...,...,...,...,...,...,...,...
185,v8,hhsdbg,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[2,3,2]",NaN,NaN,NaN,"h,s,d,b,g"
186,v9,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g"
187,v10,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g"
188,v11,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g"
189,v12,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g"

### Split sequence into single actions

In [67]:
for row in range(0, len(df)):
    sequence = df.at[row, 'sequence']
    for char in range(0,len(sequence)):
        col_name = 'seq' + str(char + 1)
        df.at[row, col_name] = sequence[char]

In [68]:
df

,ID,sequence,coordinates,start_coordinates,strong_k,mid_k,food_k,containment,seq1,seq2,...,seq8,seq9,seq10,seq11,seq12,seq13,seq14,seq15,seq16,seq17
0,a1,pocgkr,"p: (0.008034,0.957082,0.6890539999999999);o: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,p,o,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a3,cgwpcfks,"c: (-0.525007,0.923283,0.438);g: (-0.595001,1....","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,c,g,...,s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a5,kfsfkspwg,"k: (-0.07699199999999999,0.733425,0.531662);f:...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,k,f,...,w,g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a11,pfkswkfsococg,"p: (0.008034,0.957082,0.6890539999999999);p: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,p,f,...,s,o,c,o,c,g,NaN,NaN,NaN,NaN
4,a13,wptgkfsoc,"w: (-0.196022,1.35572,0.466005);p: (0.008034,0...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,w,p,...,o,c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,v8,hhsdbg,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[2,3,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,v9,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,v10,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,v11,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,v12,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Split start coordinates in x,y,z for each step

In [69]:
for row in range(0, len(df)):
    start_coords = ast.literal_eval(df.at[row, 'start_coordinates'])
    for elem in range(0, len(start_coords)):
        coords = start_coords[elem]
        
        for i in range(0, len(coords)):
            if i == 0:
                col_name_x = 'start_coords' + str(elem + 1) + '.x'
                df.at[row, col_name_x] = coords[i]
            elif i == 1:
                col_name_y = 'start_coords' + str(elem + 1) + '.y'
                df.at[row, col_name_y] = coords[i]
            elif i == 2:
                col_name_z = 'start_coords' + str(elem + 1) + '.z'
                df.at[row, col_name_z] = coords[i]

In [70]:
df.drop(['start_coordinates'], inplace=True, axis=1)

In [71]:
df

,ID,sequence,coordinates,strong_k,mid_k,food_k,containment,seq1,seq2,seq3,...,start_coords14.z,start_coords15.x,start_coords15.y,start_coords15.z,start_coords16.x,start_coords16.y,start_coords16.z,start_coords17.x,start_coords17.y,start_coords17.z
0,a1,pocgkr,"p: (0.008034,0.957082,0.6890539999999999);o: (...",t,"p,o",NaN,NaN,p,o,c,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
1,a3,cgwpcfks,"c: (-0.525007,0.923283,0.438);g: (-0.595001,1....",t,"p,o",NaN,NaN,c,g,w,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
2,a5,kfsfkspwg,"k: (-0.07699199999999999,0.733425,0.531662);f:...",t,"p,o",NaN,NaN,k,f,s,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
3,a11,pfkswkfsococg,"p: (0.008034,0.957082,0.6890539999999999);p: (...",t,"p,o",NaN,NaN,p,f,k,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
4,a13,wptgkfsoc,"w: (-0.196022,1.35572,0.466005);p: (0.008034,0...",t,"p,o",NaN,NaN,w,p,t,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,v8,hhsdbg,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,v9,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,v10,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,v11,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,v12,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
for row in range(0, len(df)):
    sequence = df.at[row, 'sequence']
    for char in sequence:
        col_name_c = str(char) + '.containment'
        col_name_k_strong = str(char) + '.strong_k'
        col_name_k_mid = str(char) + '.mid_k'
        col_name_k_food = str(char) + '.food_k'
        
        if pd.notna(df.at[row, 'containment']) and char in df.at[row, 'containment']:
            df.at[row, col_name_c] = 1
        else:
            df.at[row, col_name_c] = 0

In [80]:
df

,ID,sequence,coordinates,strong_k,mid_k,food_k,containment,seq1,seq2,seq3,...,n.containment,z.containment,m.containment,x.containment,b.containment,d.containment,l.containment,a.containment,h.containment,q.containment
0,a1,pocgkr,"p: (0.008034,0.957082,0.6890539999999999);o: (...",t,"p,o",NaN,NaN,p,o,c,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a3,cgwpcfks,"c: (-0.525007,0.923283,0.438);g: (-0.595001,1....",t,"p,o",NaN,NaN,c,g,w,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a5,kfsfkspwg,"k: (-0.07699199999999999,0.733425,0.531662);f:...",t,"p,o",NaN,NaN,k,f,s,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a11,pfkswkfsococg,"p: (0.008034,0.957082,0.6890539999999999);p: (...",t,"p,o",NaN,NaN,p,f,k,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a13,wptgkfsoc,"w: (-0.196022,1.35572,0.466005);p: (0.008034,0...",t,"p,o",NaN,NaN,w,p,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,v8,hhsdbg,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN
186,v9,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN
187,v10,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN
188,v11,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN
189,v12,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...",NaN,NaN,NaN,"h,s,d,b,g",h,h,s,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN