In [128]:
import ast
import pandas as pd
from datetime import datetime

In [129]:
df = pd.read_csv('rnn_task_environments_2021-03-17.csv', header=0)

In [130]:
df

,ID,sequence,coordinates,start_coordinates,strong_k,mid_k,food_k,containment
0,a1,pocgkr,"p: (0.008034,0.957082,0.6890539999999999);o: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
1,a3,cgwpcfks,"c: (-0.525007,0.923283,0.438);g: (-0.595001,1....","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
2,a5,kfsfkspwg,"k: (-0.07699199999999999,0.733425,0.531662);f:...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
3,a11,pfkswkfsococg,"p: (0.008034,0.957082,0.6890539999999999);p: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
4,a13,wptgkfsoc,"w: (-0.196022,1.35572,0.466005);p: (0.008034,0...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN
...,...,...,...,...,...,...,...,...
185,v8,hhsdbg,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[2,3,2]",NaN,NaN,NaN,"h,s,d,b,g"
186,v9,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g"
187,v10,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g"
188,v11,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g"
189,v12,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g"

### Split sequence into single actions

In [131]:
for row in range(0, len(df)):
    sequence = df.at[row, 'sequence']
    for char in range(0,len(sequence)):
        col_name = 'seq' + str(char + 1)
        df.at[row, col_name] = sequence[char]

In [132]:
df

,ID,sequence,coordinates,start_coordinates,strong_k,mid_k,food_k,containment,seq1,seq2,...,seq8,seq9,seq10,seq11,seq12,seq13,seq14,seq15,seq16,seq17
0,a1,pocgkr,"p: (0.008034,0.957082,0.6890539999999999);o: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,p,o,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a3,cgwpcfks,"c: (-0.525007,0.923283,0.438);g: (-0.595001,1....","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,c,g,...,s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a5,kfsfkspwg,"k: (-0.07699199999999999,0.733425,0.531662);f:...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,k,f,...,w,g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a11,pfkswkfsococg,"p: (0.008034,0.957082,0.6890539999999999);p: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,p,f,...,s,o,c,o,c,g,NaN,NaN,NaN,NaN
4,a13,wptgkfsoc,"w: (-0.196022,1.35572,0.466005);p: (0.008034,0...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,w,p,...,o,c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,v8,hhsdbg,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[2,3,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,v9,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,v10,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,v11,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,v12,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Split start coordinates in x,y,z for each step

In [133]:
for row in range(0, len(df)):
    start_coords = ast.literal_eval(df.at[row, 'start_coordinates'])
    for elem in range(0, len(start_coords)):
        coords = start_coords[elem]
        
        for i in range(0, len(coords)):
            if i == 0:
                col_name_x = 'start_coords' + str(elem + 1) + '.x'
                df.at[row, col_name_x] = coords[i]
            elif i == 1:
                col_name_y = 'start_coords' + str(elem + 1) + '.y'
                df.at[row, col_name_y] = coords[i]
            elif i == 2:
                col_name_z = 'start_coords' + str(elem + 1) + '.z'
                df.at[row, col_name_z] = coords[i]

In [134]:
df

,ID,sequence,coordinates,start_coordinates,strong_k,mid_k,food_k,containment,seq1,seq2,...,start_coords14.z,start_coords15.x,start_coords15.y,start_coords15.z,start_coords16.x,start_coords16.y,start_coords16.z,start_coords17.x,start_coords17.y,start_coords17.z
0,a1,pocgkr,"p: (0.008034,0.957082,0.6890539999999999);o: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,p,o,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
1,a3,cgwpcfks,"c: (-0.525007,0.923283,0.438);g: (-0.595001,1....","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,c,g,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
2,a5,kfsfkspwg,"k: (-0.07699199999999999,0.733425,0.531662);f:...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,k,f,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
3,a11,pfkswkfsococg,"p: (0.008034,0.957082,0.6890539999999999);p: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,p,f,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
4,a13,wptgkfsoc,"w: (-0.196022,1.35572,0.466005);p: (0.008034,0...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,w,p,...,0.74,0.513,-0.531,0.74,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,v8,hhsdbg,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[2,3,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,v9,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,v10,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,v11,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,v12,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get unique characters from sequences

In [135]:
vocabulary = set()
for row in range(0, len(df)):
    sequence = df.at[row, 'sequence']
    for char in range(0, len(sequence)):
        vocabulary.add(sequence[char])

### Split parameter info into true/false values for each item

In [136]:
for row in range(0, len(df)):
    sequence = df.at[row, 'sequence']

    for char in vocabulary:
        col_name_c = str(char) + '.containment'
        col_name_k_strong = str(char) + '.strong_k'
        col_name_k_mid = str(char) + '.mid_k'
        col_name_k_food = str(char) + '.food_k'
        
        if pd.notna(df.at[row, 'containment']) and char in df.at[row, 'containment']:
            df.at[row, col_name_c] = 1
        else:
            df.at[row, col_name_c] = 0
            
        if pd.notna(df.at[row, 'strong_k']) and char in df.at[row, 'strong_k']:
            df.at[row, col_name_k_strong] = 1
        else:
            df.at[row, col_name_k_strong] = 0
            
        if pd.notna(df.at[row, 'mid_k']) and char in df.at[row, 'mid_k']:
            df.at[row, col_name_k_mid] = 1
        else:
            df.at[row, col_name_k_mid] = 0
            
        if pd.notna(df.at[row, 'food_k']) and char in df.at[row, 'food_k']:
            df.at[row, col_name_k_food] = 1
        else:
            df.at[row, col_name_k_food] = 0

In [137]:
df

,ID,sequence,coordinates,start_coordinates,strong_k,mid_k,food_k,containment,seq1,seq2,...,t.mid_k,t.food_k,a.containment,a.strong_k,a.mid_k,a.food_k,h.containment,h.strong_k,h.mid_k,h.food_k
0,a1,pocgkr,"p: (0.008034,0.957082,0.6890539999999999);o: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,p,o,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,a3,cgwpcfks,"c: (-0.525007,0.923283,0.438);g: (-0.595001,1....","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,c,g,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,a5,kfsfkspwg,"k: (-0.07699199999999999,0.733425,0.531662);f:...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,k,f,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,a11,pfkswkfsococg,"p: (0.008034,0.957082,0.6890539999999999);p: (...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,p,f,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,a13,wptgkfsoc,"w: (-0.196022,1.35572,0.466005);p: (0.008034,0...","[-0.451354,-0.413918,0.156247],[0.513,-0.531,0...",t,"p,o",NaN,NaN,w,p,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,v8,hhsdbg,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[2,3,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
186,v9,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
187,v10,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
188,v11,hhsgdb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,2,2],[0,1,3]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
189,v12,hhsdgb,"h: (0,4,1);s: (0,2,2);d: (0,1,3);b: (2,3,2);g:...","[1,3,2],[0,4,1],[0,4,1],[0,2,2],[0,1,3],[0,2,2]",NaN,NaN,NaN,"h,s,d,b,g",h,h,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

### Split up coordinates into x,y,z for each item

In [138]:
for row in range(0, len(df)):
    coordinates = {key: ast.literal_eval(value) for key, value in
                   (elem.split(': ') for elem in df.at[row, 'coordinates'].split(';'))}
    
    for item in coordinates:
        coords = coordinates[item]
        
        for i in range(0, len(coords)):
            if i == 0:
                col_name_x = 'coordinates_' + str(item) + '.x'
                df.at[row, col_name_x] = coords[i]
            elif i == 1:
                col_name_y = 'coordinates_' + str(item) + '.y'
                df.at[row, col_name_y] = coords[i]
            elif i == 2:
                col_name_z = 'coordinates_' + str(item) + '.z'
                df.at[row, col_name_z] = coords[i]

In [139]:
to_drop = ['coordinates', 'ID', 'strong_k', 'mid_k', 'food_k', 'containment', 'start_coordinates']

df.drop(to_drop, axis=1, inplace=True)

In [140]:
df

,sequence,seq1,seq2,seq3,seq4,seq5,seq6,seq7,seq8,seq9,...,coordinates_l.z,coordinates_a.x,coordinates_a.y,coordinates_a.z,coordinates_h.x,coordinates_h.y,coordinates_h.z,coordinates_q.x,coordinates_q.y,coordinates_q.z
0,pocgkr,p,o,c,g,k,r,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,cgwpcfks,c,g,w,p,c,f,k,s,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,kfsfkspwg,k,f,s,f,k,s,p,w,g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pfkswkfsococg,p,f,k,s,w,k,f,s,o,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,wptgkfsoc,w,p,t,g,k,f,s,o,c,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,hhsdbg,h,h,s,d,b,g,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,4.0,1.0,NaN,NaN,NaN
186,hhsdgb,h,h,s,d,g,b,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,4.0,1.0,NaN,NaN,NaN
187,hhsgdb,h,h,s,g,d,b,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,4.0,1.0,NaN,NaN,NaN
188,hhsgdb,h,h,s,g,d,b,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,4.0,1.0,NaN,NaN,NaN
189,hhsdgb,h,h,s,d,g,b,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,4.0,1.0,NaN,NaN,NaN

In [141]:
date = datetime.today().strftime('%Y-%m-%d')
filename = 'rnn_task_environments_' + str(date) + '.csv'

filename

'rnn_task_environments_2021-07-09.csv'

In [142]:
#df.to_csv(filename, header=True, index=True)