In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('data/EPIC_2018_original_annotation_all_timestamps.csv', header=0)

In [16]:
df

,uid,participant_id,video_id,narration,start_timestamp,stop_timestamp,start_frame,stop_frame,verb,verb_class,...,all_nouns,all_noun_classes,grid_location,prior_grid,lhand_vposition,lhand_hposition,rhand_vposition,rhand_hposition,hand in use,Unnamed: 21
0,0,P01,P01_01,open door,00:00.1,00:03.4,8,202,open,2,...,['door'],[8],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,P01,P01_01,turn on light,00:04.4,00:06.2,262,370,turn-on,12,...,['light'],[113],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,P01,P01_01,close door,00:07.0,00:09.5,418,569,close,3,...,['door'],[8],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,P01,P01_01,open fridge,00:12.8,00:14.0,766,839,open,2,...,['fridge'],[10],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,P01,P01_01,take celery,00:15.2,00:16.4,915,983,take,0,...,['celery'],[185],"(0,3)","(0,0)",0.0,0.0,0.0,0,right,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28467,39232,P31,P31_14,wash glass,03:53.2,04:17.7,13991,15462,wash,4,...,['glass'],[16],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28468,39233,P31,P31_14,dry hands,04:51.2,04:58.9,17472,17935,dry,11,...,['hand'],[12],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28469,39234,P31,P31_14,pick up napkins,04:59.5,05:02.2,17971,18134,pick-up,0,...,['napkin'],[97],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28470,39235,P31,P31_14,put down napkins,05:02.3,05:10.8,18140,18645,put-down,1,...,['napkin'],[97],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28471,39236,P31,P31_14,close door,05:10.9,05:12.1,18651,18724,close,3,...,['door'],[8],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
grid_location_set = df[pd.notna(df['grid_location'])]

In [12]:
IDs = grid_location_set['video_id'].unique()

In [14]:
len(IDs)

137

In [17]:
annotated_episodes = df[df['video_id'].isin(IDs)]

In [18]:
annotated_episodes

,uid,participant_id,video_id,narration,start_timestamp,stop_timestamp,start_frame,stop_frame,verb,verb_class,...,all_nouns,all_noun_classes,grid_location,prior_grid,lhand_vposition,lhand_hposition,rhand_vposition,rhand_hposition,hand in use,Unnamed: 21
0,0,P01,P01_01,open door,00:00.1,00:03.4,8,202,open,2,...,['door'],[8],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,P01,P01_01,turn on light,00:04.4,00:06.2,262,370,turn-on,12,...,['light'],[113],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,P01,P01_01,close door,00:07.0,00:09.5,418,569,close,3,...,['door'],[8],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,P01,P01_01,open fridge,00:12.8,00:14.0,766,839,open,2,...,['fridge'],[10],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,P01,P01_01,take celery,00:15.2,00:16.4,915,983,take,0,...,['celery'],[185],"(0,3)","(0,0)",0.0,0.0,0.0,0,right,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27916,38583,P30,P30_10,continue washing hob surface,12:45.4,12:48.7,45925,46119,wash,4,...,['surface:hob'],[78],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27917,38584,P30,P30_10,continue washing hob surface,12:48.3,12:52.4,46097,46345,wash,4,...,['surface:hob'],[78],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27918,38585,P30,P30_10,continue washing hob surface,12:49.1,12:54.4,46145,46465,wash,4,...,['surface:hob'],[78],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27919,38586,P30,P30_10,continue washing hob surface,12:51.9,12:54.5,46312,46468,wash,4,...,['surface:hob'],[78],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27920,38587,P30,P30_10,dry hands,13:06.0,13:09.6,47162,47374,dry,11,...,['hand'],[12],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN