In [3]:
import pandas as pd

In [1]:
test = ['00:11.2', '00:01.7', '01:00.1']

In [2]:
sorted(test)

['00:01.7', '00:11.2', '01:00.1']

In [29]:
df = pd.read_csv('data/EPIC_100_annotated_episodes_amended.csv', header=0, index_col=False)

In [34]:
df

,Unnamed: 0,narration_id,participant_id,video_id,narration_timestamp,start_timestamp,stop_timestamp,start_frame,stop_frame,narration,...,all_nouns,all_noun_classes,grid_location,prior_grid,lhand_vposition,lhand_hposition,rhand_vposition,rhand_hposition,hand in use,Unnamed: 22
0,318.0,P01_105_0,P01,P01_105,00:01.1,00:01.0,00:02.2,51.0,109.0,pick up container,...,['container'],[21],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,319.0,P01_105_1,P01,P01_105,00:02.6,00:02.3,00:03.5,114.0,175.0,open cupboard,...,['cupboard'],[3],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,430.0,P01_105_2,P01,P01_105,00:04.6,00:03.8,00:05.0,190.0,248.0,pick up container,...,['container'],[21],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,541.0,P01_105_3,P01,P01_105,00:05.1,00:05.2,00:05.7,258.0,283.0,put down containers,...,['container'],[21],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,652.0,P01_105_4,P01,P01_105,00:06.4,00:05.8,00:07.2,288.0,358.0,open container,...,['container'],[21],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23556,38675.0,P37_102_95,P37,P37_102,07:18.4,07:18.4,07:28.4,21919.0,22418.0,cut carrots into sticks,...,"['carrot', 'stick']","[41, 228]","(3,2)","(3,2)",-1,-1.0,0,0,right,NaN
23557,38676.0,P37_102_96,P37,P37_102,07:28.9,07:29.1,07:29.7,22455.0,22483.0,take carrots,...,['carrot'],[41],"(3,2)","(3,2)",0,0.0,-1,-1,left,NaN
23558,38677.0,P37_102_97,P37,P37_102,07:29.4,07:29.5,07:32.2,22476.0,22608.0,put carrots in plate,...,"['carrot', 'plate']","[41, 2]","(3,2)","(3,2)",0,0.0,-1,-1,left,NaN
23559,38678.0,P37_102_98,P37,P37_102,07:33.2,07:33.4,07:52.8,22670.0,23638.0,cut carrots into sticks,...,"['carrot', 'stick']","[41, 228]","(3,2)","(3,2)",-1,-1.0,0,0,right,NaN
23560,38679.0,P37_102_99,P37,P37_102,07:53.4,07:52.9,07:53.8,23643.0,23689.0,take carrots,...,['carrot'],[41],"(3,2)","(3,2)",0,0.0,-1,-1,left,NaN

In [30]:
df_new = pd.DataFrame()

In [31]:
for video_id in df['video_id'].unique():
    id_df = df.loc[df['video_id'] == video_id]
    id_df.sort_values('start_timestamp', inplace=True)
    df_new = df_new.append(id_df)

/home/pwenzl/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [33]:
df_new

,Unnamed: 0,narration_id,participant_id,video_id,narration_timestamp,start_timestamp,stop_timestamp,start_frame,stop_frame,narration,...,all_nouns,all_noun_classes,grid_location,prior_grid,lhand_vposition,lhand_hposition,rhand_vposition,rhand_hposition,hand in use,Unnamed: 22
0,318.0,P01_105_0,P01,P01_105,00:01.1,00:01.0,00:02.2,51.0,109.0,pick up container,...,['container'],[21],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,319.0,P01_105_1,P01,P01_105,00:02.6,00:02.3,00:03.5,114.0,175.0,open cupboard,...,['cupboard'],[3],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,430.0,P01_105_2,P01,P01_105,00:04.6,00:03.8,00:05.0,190.0,248.0,pick up container,...,['container'],[21],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,541.0,P01_105_3,P01,P01_105,00:05.1,00:05.2,00:05.7,258.0,283.0,put down containers,...,['container'],[21],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,652.0,P01_105_4,P01,P01_105,00:06.4,00:05.8,00:07.2,288.0,358.0,open container,...,['container'],[21],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23463,38582.0,P37_102_145,P37,P37_102,11:12.4,11:06.7,11:13.0,33334.0,33651.0,take plate,...,['plate'],[2],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23464,38583.0,P37_102_146,P37,P37_102,11:14.2,11:13.0,11:15.4,33651.0,33771.0,put plates down,...,['plate'],[2],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23465,38584.0,P37_102_147,P37,P37_102,11:16.2,11:15.4,11:16.8,33772.0,33840.0,take packing bag,...,['bag:packing'],[19],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23466,38585.0,P37_102_148,P37,P37_102,11:17.2,11:16.8,11:17.7,33842.0,33882.0,put packing bag down,...,['bag:packing'],[19],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23467,38586.0,P37_102_149,P37,P37_102,11:18.9,11:17.7,11:20.0,33886.0,33999.0,put knife down,...,['knife'],[4],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df_new.to_csv('data/EPIC_100_annotated_episodes_amended2.csv', index=False, header=True)